version: "3"
services:
  go-service-with-metrics:
    build: .
    ports:
      - 8080:8080
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./infra/prometheus:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    depends_on:
      - go-service-with-metrics
  grafana:
      image: grafana/grafana:latest
      volumes:
        - ./infra/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
      ports:
        - 3000:3000
      depends_on:
        - prometheus